Created rest api.
htmlacademy-nodejs/1819879-typoteka-3 pull request #10
Opened 2022-02-01 21:27 UTC by shestakov-rv

2022-02-07 01:05 UTC, Krabaton requested changes

2022-02-07 01:05 UTC, Krabaton commented on package.json
> +    "nanoid": "3.2.0",
В этом пакете у же нет особой необходимости https://nodejs.org/dist/latest-v16.x/docs/api/crypto.html#cryptorandomuuidoptions

2022-02-07 01:05 UTC, Krabaton commented on src/service/api/search.js
> +      res.status(HttpCode.BAD_REQUEST).json(``);
Забыл `return`

2022-02-07 01:05 UTC, Krabaton commented on src/service/cli/server.js
>  server.use(express.json());
Можно поставить ограничение на limit. По умолчанию там аж 100kb
https://expressjs.com/ru/api.html#express.json

2022-02-07 01:05 UTC, Krabaton commented on src/service/cli/server.js
> +  console.error(`An error occured on processing request: ${err.message}`);
Тут если сюда попадаем мы клиенту ничего не отвечаем, просто висим, не очень хорошо. Лучше скидывать, что 500 произошла

2022-02-07 01:05 UTC, Krabaton commented on src/service/middlewares/entity-key-validator.js
> +    res.status(HttpCode.BAD_REQUEST).send(`Bad request`);
Тоже пропущен `return`

2022-02-07 01:05 UTC, Krabaton commented on src/utils.js
> +module.exports.includesQuery = (text, query) => {
А зачем мы здесь применили патттерн `SubStack` ?

2022-02-08 18:01 UTC, shestakov-rv commented on src/utils.js
> +module.exports.includesQuery = (text, query) => {
Просто вынес в чистую функцию, посчитал логичным скрыть в утилитарный уровень работу с вхождением строки с учётом пробелов и регистра.

2022-02-10 00:04 UTC, merged