Added read data from files.
htmlacademy-nodejs/1819879-typoteka-3 pull request #5
Opened 2021-12-29 20:36 UTC by shestakov-rv

2021-12-31 17:29 UTC, Krabaton requested changes

2021-12-31 17:29 UTC, Krabaton commented on src/service/cli/generate.js
> +    return content.trim().split(`\n`);
Мало операций. Мы пропускаем пустые строки. Мы пропускаем пустые символы вокруг сообщений. Надо чистить каждую строку и убирать пустые строки.

2021-12-31 17:29 UTC, Krabaton commented on src/service/cli/generate.js
> +  const sentencesData = await readFile(SENTENCES_FILE_NAME);
На самом деле три await  это не очень быстро, лучше их всех дождаться Promise.all

2021-12-31 22:11 UTC, shestakov-rv commented on src/service/cli/generate.js
> +    return content.trim().split(`\n`);
Поправил

2021-12-31 22:11 UTC, shestakov-rv commented on src/service/cli/generate.js
> +  const sentencesData = await readFile(SENTENCES_FILE_NAME);
Поправил

2022-01-01 10:34 UTC, Krabaton approved these changes

2022-01-01 10:34 UTC, Krabaton commented on src/service/cli/generate.js
>      writeFile(randomCategoriesJson).then();
почему не await? Это же понятнее чем then дописать.

2022-01-01 10:34 UTC, Krabaton commented on src/service/cli/generate.js
> +});
Ох, имхо так понятнее
```js
const getRandomPosts = async (count) =>  { 
const [titlesData, categoriesData, sentencesData] = await Promise.all([
  readFile(TITLES_FILE_NAME),
  readFile(CATEGORIES_FILE_NAME),
  readFile(SENTENCES_FILE_NAME)
])
  return new Array(count).fill(null).map(() => getRandomPost(titlesData, categoriesData, sentencesData));
};
```

2022-01-01 10:34 UTC, merged